package interfazgrafica.VentanasEnComun;

import interfazgrafica.ClasesBase.Empleado;
import interfazgrafica.ClasesBase.Cliente;
import interfazgrafica.ClasesBase.Usuario;
import interfazgrafica.ClasesBase.Planta;
import interfazgrafica.ClasesBase.Dueño;
import interfazgrafica.VentanasCliente.MenuClientes;
import interfazgrafica.VentanasUsuario.MenuPrincipal;
import java.util.HashSet;
import java.util.Set;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    /**
     * Set con todos los usuarios.
     */
    Set<Usuario> setUsuarios;
    /**
     * Set con todos los clientes registrados.
     */
    Set<Cliente> setClientes;
    /**
     * Set con todas las plantas.
     */
    Set<Planta> plantas = new HashSet<>();
    /**
     * Login es la ventana de acceso al programa.
     * Lee los archivos Usuarios.txt y Clientes.txt
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setUsuarios = new HashSet();
        setClientes = new HashSet();
        try{
            this.inUsuarios();
        }
        catch(IOException ioe){
            JOptionPane.showMessageDialog(null,"No se pudo abrir el archivo Usuarios.txt. Contacte a sus desarrolladores","Error",JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null,"El programa se cerrara de forma segura","Info",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        try{
            this.inClientes();
        }
        catch(IOException ioe){
            JOptionPane.showMessageDialog(null,"No se pudo abrir el archivo Clientes.txt. Contacte a sus desarrolladores","Error",JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null,"El programa se cerrara de forma segura","Info",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                int reply = JOptionPane.showConfirmDialog(null,"Esta seguro que desea salir del programa?","Atencion",JOptionPane.YES_NO_OPTION);
                if(reply == JOptionPane.YES_OPTION){
                    try {
                        outClientes();
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null,"No se pudo escribir el archivo Clientes.txt. Contacte a sus desarrolladores","Error",JOptionPane.ERROR_MESSAGE);
                    }
                    System.exit(0);
                }                    
            }
        });
        jButtonLogin.setToolTipText("Permite loguearse en el sistema siempre y cuando los datos ingresados sean correctos");
        jButtonRegistrarse.setToolTipText("Permite registrarse como cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanelFondo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegistrarse = new javax.swing.JButton();
        jPasswordFieldContraLogin = new javax.swing.JPasswordField();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jLabelContrasena = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 290));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Login"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jButtonLogin.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButtonLogin.setText("Ingresar");
        jButtonLogin.setPreferredSize(new java.awt.Dimension(130, 25));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonRegistrarse.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.setPreferredSize(new java.awt.Dimension(120, 25));
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });

        jLabelContrasena.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabelContrasena.setText("Contraseña");

        jLabelUser.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jLabelUser.setText("Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/Iconos/Vivero.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelContrasena))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldContraLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldContraLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String user = jTextFieldUserLogin.getText();
        String contra = new String(jPasswordFieldContraLogin.getPassword());
        boolean estaBien = true;
        boolean found = false;
        Usuario usuario = null;
        Cliente cliente = null;
        
        if (user.equals("") || contra.equals("")){
            JOptionPane.showMessageDialog(null,"Algunos campos no se han completado. Intente nuevamente." ,"Atencion" , JOptionPane.WARNING_MESSAGE);
            estaBien = false;
        }
        
        if (estaBien){
            Iterator i = setClientes.iterator();
            while(i.hasNext()){
                cliente =(Cliente)i.next();
                if (cliente.getUsuario().equals(user) && cliente.getContrasenia().equals(contra)){
                    found = true;
                    break;
                }
            }
            if(found){
                MenuClientes mc = new MenuClientes(setClientes,cliente,setUsuarios);
                mc.setVisible(true);
                mc.setLocationRelativeTo(this);
                this.dispose();
            }
            else{
                Iterator j = setUsuarios.iterator();
                while(j.hasNext()){
                    usuario =(Usuario)j.next();
                    if (usuario.getUsuario().equals(user) && usuario.getContrasenia().equals(contra)){
                        found = true;
                        break;
                    }
                }
                if(found){
                    MenuPrincipal mp = new MenuPrincipal(setUsuarios,setClientes,usuario);
                    mp.setLocationRelativeTo(null);
                    mp.setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(null,"El usuario o la contraseña son inválidos. Intente nuevamente." ,"Atencion" , JOptionPane.WARNING_MESSAGE);
            }
        }
                
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        Registrarse r = new Registrarse(setClientes,this,setUsuarios);
        r.setVisible(true);
        r.setLocationRelativeTo(this);
        jTextFieldUserLogin.setText("");
        jPasswordFieldContraLogin.setText("");
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    
    public void inUsuarios() throws FileNotFoundException, IOException{
       File f = new File("Usuarios.txt");
       FileReader leo = new FileReader(f);
       BufferedReader leer = new BufferedReader(leo);
       String tipo,auxParse;
       while((tipo = leer.readLine()) != null){
            if(tipo.equals("Dueno")){
                Dueño aux1 = new Dueño();
                aux1.setNombre(leer.readLine().substring(8));
                aux1.setApellido(leer.readLine().substring(10));
                auxParse = leer.readLine().substring(5);
                aux1.setDni(Integer.parseInt(auxParse));
                aux1.setTelefonoMovil(Long.parseLong(leer.readLine().substring(16)));
                aux1.setTelefonoFijo(Long.parseLong(leer.readLine().substring(15)));
                aux1.setFechaDeNacimiento(leer.readLine().substring(21));
                aux1.setUsuario(leer.readLine().substring(9));
                aux1.setContrasenia(leer.readLine().substring(12));
                auxParse = leer.readLine().substring(9);
                aux1.setPuntaje(Integer.parseInt(auxParse));
                auxParse = leer.readLine().substring(18);
                aux1.setEspeciesCreadas(Integer.parseInt(auxParse));
                auxParse = leer.readLine().substring(8);
                aux1.setEscala(Integer.parseInt(auxParse));
                setUsuarios.add(aux1);
                leer.readLine();
            }
            else
            {
                Empleado aux2 = new Empleado();
                aux2.setNombre(leer.readLine().substring(8));
                aux2.setApellido(leer.readLine().substring(10));
                auxParse = leer.readLine().substring(5);
                aux2.setDni(Integer.parseInt(auxParse));
                aux2.setTelefonoMovil(Long.parseLong(leer.readLine().substring(16)));
                aux2.setTelefonoFijo(Long.parseLong(leer.readLine().substring(15)));
                aux2.setFechaDeNacimiento(leer.readLine().substring(21));
                aux2.setUsuario(leer.readLine().substring(9));
                aux2.setContrasenia(leer.readLine().substring(12));
                auxParse = leer.readLine().substring(9);
                aux2.setPuntaje(Integer.parseInt(auxParse));
                auxParse = leer.readLine().substring(8);
                aux2.setSueldo(Double.parseDouble(auxParse));
                auxParse = leer.readLine().substring(12);
                aux2.setAntiguedad(Integer.parseInt(auxParse));
                auxParse = leer.readLine().substring(12);
                aux2.setBonoExtra(Double.parseDouble(auxParse));
                setUsuarios.add(aux2);
                leer.readLine();
               
            }
        }
        leer.close();
       }
    
    public void inClientes() throws FileNotFoundException, IOException{
       File f = new File("Clientes.txt");
       FileReader leo = new FileReader(f);
       BufferedReader leer = new BufferedReader(leo);
       String auxParse;
       while((auxParse = leer.readLine()) != null){
            Cliente cliente = new Cliente();
            cliente.setCodigo(Integer.parseInt(auxParse.substring(20)));
            cliente.setNombre(leer.readLine().substring(8));
            cliente.setDireccion(leer.readLine().substring(11));
            cliente.setEmail(leer.readLine().substring(8));
            auxParse = leer.readLine();
            cliente.setCuil(Long.parseLong(auxParse.substring(6)));
            auxParse = leer.readLine();
            cliente.setTipo(Boolean.parseBoolean(auxParse.substring(6)));
            cliente.setFechaDeIngreso(leer.readLine().substring(18));
            cliente.setUsuario(leer.readLine().substring(9));
            cliente.setContrasenia(leer.readLine().substring(12));
            setClientes.add(cliente);
            leer.readLine();
       }
       leer.close();
    }
    
    public void outClientes() throws IOException{
        File f = new File("Clientes.txt");
        FileWriter escribo = new FileWriter(f);
        BufferedWriter escribir = new BufferedWriter(escribo);
        Iterator i = this.setClientes.iterator();
        while(i.hasNext()){
            Cliente c = (Cliente)i.next();
            escribir.write(c.toString());
            escribir.newLine();
        }
        escribir.close();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPasswordField jPasswordFieldContraLogin;
    private javax.swing.JTextField jTextFieldUserLogin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


    
}
