package interfazgrafica.VentanasUsuario;

import interfazgrafica.ClasesBase.Cliente;
import interfazgrafica.ClasesBase.Empleado;
import interfazgrafica.ClasesBase.Usuario;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class CargarEmpleado extends javax.swing.JFrame {
    /**
     * set de Usuario, almacenará los todos los usuarios
     */
    private Set <Usuario> setUsuarios;
    /**
     * set de Cliente, almacenará los todos los clientes
     */
    private Set <Cliente> setClientes;
    /**
     * Padre
     */
    private MenuPrincipal padre;
    
    public CargarEmpleado() {
        initComponents();
    }
    
    
    /**
     * Constructor de la clase, inicializa los sets y define la operación a realizarse cuando se oprime la x para cerrar la ventana
     * @param usuarios Set de Usuario, contiene a los usuarios
     * @param clientes Set de Cliente, contiene a los clientes
     * @param mp Menu Principal, jFrame padre de esta ventana
     */
    public CargarEmpleado(Set<Usuario> usuarios,Set <Cliente> clientes,MenuPrincipal mp) {
        initComponents();
        this.setUsuarios = usuarios;
        this.setClientes = clientes;
        this.padre = mp;
        this.addWindowListener(new WindowAdapter(){
        @Override
            public void windowClosing(WindowEvent e){
                int reply = JOptionPane.showConfirmDialog(null,"Esta seguro que desea salir? Perdera los datos del nuevo empleado a cargar","Atencion",JOptionPane.YES_NO_OPTION);
                if(reply == JOptionPane.YES_OPTION){
                    padre.setEnabled(true);
                    dispose();
                }     
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabelNombreEmpleado = new javax.swing.JLabel();
        jLabelApellidoEmpleado = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldApellidoEmpleado = new javax.swing.JTextField();
        jTextFieldNombreEmpleado = new javax.swing.JTextField();
        jTextFieldUsuarioEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCaracteristicaTM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroTM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseñaEmpleado = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCaracteristicaTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumeroTF = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JFormattedTextField();
        jTextFieldSueldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonConfirmarEmpleado = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jDateChooserFechaDeNacimiento = new com.toedter.calendar.JDateChooser();
        jSpinnerAntiguedad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 520));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Cargar empleado"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabelNombreEmpleado.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabelNombreEmpleado.setText("Nombre/s");

        jLabelApellidoEmpleado.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabelApellidoEmpleado.setText("Apellido/s");

        jLabelDNI.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabelDNI.setText("D.N.I.");

        jLabelUsuario.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabelUsuario.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese los datos del nuevo empleado:");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel4.setText("Fecha de nacimiento");

        jLabel1.setText("-");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel2.setText("Telefono movil");

        jLabelContraseña.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabelContraseña.setText("Contraseña");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel5.setText("Telefono fijo");

        jLabel6.setText("-");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel8.setText("Sueldo ($)");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel9.setText("Antiguedad (años)");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jButtonConfirmarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfirmarEmpleado.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButtonConfirmarEmpleado.setText("Confirmar");
        jButtonConfirmarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarEmpleadoActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonConfirmarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConfirmarEmpleado))
                .addGap(25, 25, 25))
        );

        jSpinnerAntiguedad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDNI)
                            .addComponent(jLabelApellidoEmpleado)
                            .addComponent(jLabelNombreEmpleado)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelContraseña)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldContraseñaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApellidoEmpleado)
                                .addComponent(jTextFieldNombreEmpleado)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCaracteristicaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNumeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDNI)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCaracteristicaTM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNumeroTM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jDateChooserFechaDeNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreEmpleado)
                    .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoEmpleado)
                    .addComponent(jTextFieldApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldNumeroTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCaracteristicaTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCaracteristicaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNumeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldContraseñaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,"Esta seguro que desea salir? Perdera los datos del nuevo empleado a cargar","Atencion",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            padre.setEnabled(true);
            this.dispose();
        }  
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConfirmarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarEmpleadoActionPerformed
        
        String contrasenia = new String(jPasswordFieldContraseñaEmpleado.getPassword());
        int dni = 0;
        float sueldo = 0;
        long carMovil;
        long movil;
        long carFijo;
        long fijo;
        boolean estaBien = true;

        if(contrasenia.equals("")||jTextFieldApellidoEmpleado.getText().equals("")||jTextFieldNombreEmpleado.getText().equals("")||jTextFieldDNI.getText().equals("")||jTextFieldUsuarioEmpleado.getText().equals("")||jTextFieldCaracteristicaTM.getText().equals("")||jTextFieldNumeroTM.getText().equals("")||jDateChooserFechaDeNacimiento.getDateFormatString().equals("")||jTextFieldCaracteristicaTF.getText().equals("")||jTextFieldNumeroTF.getText().equals("")||jSpinnerAntiguedad.getValue().equals("")||jTextFieldSueldo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Algunos campos no se han completado. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
            estaBien = false;
        }
        
        
        if(estaBien){
            String nombre = jTextFieldNombreEmpleado.getText();
            String regex = "^[a-zA-Z][a-zA-Z\\s]*$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(nombre);
            if (!matcher.matches()){
                JOptionPane.showMessageDialog(null,"El formato del nombre es incorrecto. No puede comenzar con un espacio, contener numeros ni caracteres especiales (incluye tildes). Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;  
            }
        }
        
        if(estaBien){
            String apellido = jTextFieldApellidoEmpleado.getText();
            String regex = "^[a-zA-Z][a-zA-Z\\s]*$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(apellido);
            if (!matcher.matches()){
                JOptionPane.showMessageDialog(null,"El formato del apellido es incorrecto. No puede comenzar con un espacio, contener numeros ni caracteres especiales (incluye tildes). Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;  
            }
        }
        
        if(estaBien){   
            try{
                 dni = Integer.parseInt(jTextFieldDNI.getText());
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"El DNI debe contener solo numeros. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            if(dni>99999999||dni<1000000){
                JOptionPane.showMessageDialog(null,"El DNI ingresado no existe. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien=false;
            }
        }
        
        if(estaBien){
            Iterator i = setUsuarios.iterator();
            while(i.hasNext()){
                Usuario u = (Usuario) i.next();
                if(u.getDni() == dni){
                   JOptionPane.showMessageDialog(null,"Ya existe un empleado cargado con ese DNI. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                   estaBien = false;
                   break;
                } 
           }
        }
        
        if(estaBien){
            if(jDateChooserFechaDeNacimiento.getDate() == null){
                JOptionPane.showMessageDialog(null,"El formato de la fecha es incorrecto. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            Calendar fecha = new GregorianCalendar();
            fecha.set(2000,11,31);
            if(jDateChooserFechaDeNacimiento.getCalendar().after(fecha)){
                JOptionPane.showMessageDialog(null,"La fecha de nacimiento debe ser anterior al año 2000. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            Calendar fecha = new GregorianCalendar();
            fecha.set(1899,11,31);
            if(jDateChooserFechaDeNacimiento.getCalendar().before(fecha)){
                JOptionPane.showMessageDialog(null,"La fecha de nacimiento debe ser posterior al año 1900. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            try{
                carMovil = Long.parseLong(jTextFieldCaracteristicaTM.getText());
                movil = Long.parseLong(jTextFieldNumeroTM.getText());
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"El telefono movil solo puede contener numeros. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            try{
                carFijo = Long.parseLong(jTextFieldCaracteristicaTF.getText());
                fijo = Long.parseLong(jTextFieldNumeroTF.getText());
                
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"El telefono fijo solo puede contener numeros. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            Iterator i = setUsuarios.iterator();
            while(i.hasNext()){
                Usuario u = (Usuario) i.next();
                if(u.getUsuario().equals(jTextFieldUsuarioEmpleado.getText())){
                    JOptionPane.showMessageDialog(null,"El usuario ingresado ya existe. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                    estaBien=false;
                    break;
                }
            }
        }
        
        if(estaBien){
            Iterator i = setClientes.iterator();
            while(i.hasNext()){
                Cliente c = (Cliente) i.next();
                if(c.getUsuario().equals(jTextFieldUsuarioEmpleado.getText())){
                    JOptionPane.showMessageDialog(null,"El usuario ingresado ya existe. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                    estaBien=false;
                    break;
                }
            }
        }
        
        if(estaBien){
            if(jTextFieldUsuarioEmpleado.getText().length()<6){
                JOptionPane.showMessageDialog(null,"El usuario debe tener al menos 6 caracteres. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien=false;
            }
        }
        
        if(estaBien){
            if(jPasswordFieldContraseñaEmpleado.getPassword().length<6){
                JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos 6 caracteres. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien=false;
            }
        }
        
        if(estaBien){
            try{
                sueldo = Float.parseFloat(jTextFieldSueldo.getText());
            }
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(null,"El sueldo puede contener solo numeros y un punto. Intente nuevamente.","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien = false;
            }
        }
        
        if(estaBien){
            if(sueldo<=0){
                JOptionPane.showMessageDialog(null,"El sueldo debe ser positivo. Intente nuevamente","Advertencia",JOptionPane.WARNING_MESSAGE);
                estaBien=false;
            }
        }


        if(estaBien){
            Empleado nuevo = new Empleado();
            nuevo.setNombre(jTextFieldNombreEmpleado.getText());
            nuevo.setApellido(jTextFieldApellidoEmpleado.getText());
            nuevo.setUsuario(jTextFieldUsuarioEmpleado.getText());
            nuevo.setContrasenia(contrasenia);
            Calendar a = jDateChooserFechaDeNacimiento.getCalendar();
            int mes = a.get(Calendar.MONTH)+1;
            nuevo.setFechaDeNacimiento(a.get(Calendar.DATE)+"/"+mes+"/"+a.get(Calendar.YEAR));
            nuevo.setSueldo(sueldo);
            nuevo.setAntiguedad((int) jSpinnerAntiguedad.getValue());
            nuevo.setDni(dni);
            nuevo.setTelefonoMovil(Long.parseLong(jTextFieldCaracteristicaTM.getText()+jTextFieldNumeroTM.getText()));
            nuevo.setTelefonoFijo(Long.parseLong(jTextFieldCaracteristicaTF.getText()+jTextFieldNumeroTF.getText()));
            setUsuarios.add(nuevo);
            JOptionPane.showMessageDialog(null,"Nuevo empleado cargado","Informacion",JOptionPane.INFORMATION_MESSAGE);
            padre.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonConfirmarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmarEmpleado;
    private com.toedter.calendar.JDateChooser jDateChooserFechaDeNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidoEmpleado;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelNombreEmpleado;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldContraseñaEmpleado;
    private javax.swing.JSpinner jSpinnerAntiguedad;
    private javax.swing.JTextField jTextFieldApellidoEmpleado;
    private javax.swing.JTextField jTextFieldCaracteristicaTF;
    private javax.swing.JTextField jTextFieldCaracteristicaTM;
    private javax.swing.JFormattedTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNombreEmpleado;
    private javax.swing.JTextField jTextFieldNumeroTF;
    private javax.swing.JTextField jTextFieldNumeroTM;
    private javax.swing.JTextField jTextFieldSueldo;
    private javax.swing.JTextField jTextFieldUsuarioEmpleado;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
