package interfazgrafica.VentanasUsuario;

import interfazgrafica.Ordenadores.OrdenarDuenoPorPuntaje;
import interfazgrafica.Ordenadores.OrdenarEmpleadoPorDni;
import interfazgrafica.Ordenadores.OrdenarEmpleadoPorPuntaje;
import interfazgrafica.Ordenadores.OrdenarDuenoPorDni;
import interfazgrafica.ClasesBase.Dueño;
import interfazgrafica.ClasesBase.Empleado;
import interfazgrafica.ClasesBase.Usuario;
import java.awt.JobAttributes;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ConsultarUsuarios extends javax.swing.JFrame {
    /**
     * set de Usuario, contiene todos los usuarios del programa
     */
    private Set <Usuario> setUsuarios;
    /**
     * model la tabla jTableDuenos
     */
    private DefaultTableModel modelDuenos;
    /**
     * model de la tabla jTableEmpleados
     */
    private DefaultTableModel modelEmpleados;
    /**
     * Lista con los dueños ordenada
     */
    private List listaDuenosOrdenada;
    /**
     * Lista con los empleados ordenados
     */
    private List listaEmpleadosOrdenada;
    /**
     * jFrame Padre
     */
    private MenuPrincipal padre;
    
    public ConsultarUsuarios() {
        initComponents();
    }
    
    /**
     * Constructor de la clase, inicializa los sets y define la operación a realizarse cuando se oprime la x para cerrar la ventana
     * @param setUsuarios 
     * @param mp Menu Principal, jFrame padre de esta ventana
     */
    ConsultarUsuarios(Set<Usuario> setUsuarios,MenuPrincipal mp) {
        initComponents();
        this.setUsuarios = setUsuarios;
        padre = mp;
        modelDuenos = (DefaultTableModel) jTableDuenos.getModel();
        modelEmpleados = (DefaultTableModel) jTableEmpleados.getModel();
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                padre.setEnabled(true);
                dispose();
            }
        });
        jButton1.setToolTipText("Permite calcular el desempeño de los usuarios con respecto a las ventas y carga de plantas en el sistema");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDuenos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonOrdenarPorDNI = new javax.swing.JRadioButton();
        jRadioButtonOrdenarPorPuntaje = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Usuarios");
        setPreferredSize(new java.awt.Dimension(927, 620));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jTableDuenos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Telefono Movil", "Telefono Fijo", "Fecha de nacimiento", "Puntaje", "Especies Creadas", "Escala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDuenos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDuenos);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel1.setText("Dueños");

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Telefono fijo", "Telefono movil", "Fecha de nacimiento", "Puntaje", "Sueldo", "Antiguedad", "Bono Extra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableEmpleados);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel2.setText("Empleados");

        jButtonVolver.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jButton1.setText("Evaluar Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jRadioButtonOrdenarPorDNI.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRadioButtonOrdenarPorDNI);
        jRadioButtonOrdenarPorDNI.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jRadioButtonOrdenarPorDNI.setSelected(true);
        jRadioButtonOrdenarPorDNI.setText("Ordenar por DNI");
        jRadioButtonOrdenarPorDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonOrdenarPorDNIMouseClicked(evt);
            }
        });
        jRadioButtonOrdenarPorDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdenarPorDNIActionPerformed(evt);
            }
        });

        jRadioButtonOrdenarPorPuntaje.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRadioButtonOrdenarPorPuntaje);
        jRadioButtonOrdenarPorPuntaje.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jRadioButtonOrdenarPorPuntaje.setText("Ordenar por puntaje");
        jRadioButtonOrdenarPorPuntaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonOrdenarPorPuntajeMouseClicked(evt);
            }
        });
        jRadioButtonOrdenarPorPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOrdenarPorPuntajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOrdenarPorPuntaje)
                    .addComponent(jRadioButtonOrdenarPorDNI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonOrdenarPorDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOrdenarPorPuntaje))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton1)
                        .addGap(82, 82, 82)
                        .addComponent(jButtonVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(204, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVolver)
                            .addComponent(jButton1))
                        .addGap(144, 144, 144))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jRadioButtonOrdenarPorDNI.setSelected(true);
        listaDuenosOrdenada = new ArrayList();
        listaEmpleadosOrdenada = new ArrayList();
        Iterator i = setUsuarios.iterator();
        while(i.hasNext()){
            Usuario u = (Usuario) i.next();
            if(u instanceof Dueño){
                Dueño d = (Dueño) u;
                listaDuenosOrdenada.add(d); 
            }
            else{
                Empleado e = (Empleado) u;
                listaEmpleadosOrdenada.add(e);
            }
        }
        modelDuenos.setRowCount(0);
        modelEmpleados.setRowCount(0);
        Collections.sort(listaDuenosOrdenada, new OrdenarDuenoPorDni());
        Collections.sort(listaEmpleadosOrdenada, new OrdenarEmpleadoPorDni());
        Iterator k = listaDuenosOrdenada.listIterator();
        while(k.hasNext()){
            Dueño d = (Dueño) k.next();
            modelDuenos.addRow(new Object []{d.getNombre(),d.getApellido(),d.getDni(),d.getTelefonoMovil(),d.getTelefonoFijo(),d.getFechaDeNacimiento(),d.getPuntaje(),d.getEspeciesCreadas(),d.getEscala()});
        }
        Iterator j = listaEmpleadosOrdenada.listIterator();
        while(j.hasNext()){
            Empleado e = (Empleado) j.next();
            modelEmpleados.addRow(new Object []{e.getNombre(),e.getApellido(),e.getDni(),e.getTelefonoMovil(),e.getTelefonoFijo(),e.getFechaDeNacimiento(),e.getPuntaje(),e.getSueldo(),e.getAntiguedad(),e.getBonoExtra()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        padre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jRadioButtonOrdenarPorDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOrdenarPorDNIActionPerformed

    private void jRadioButtonOrdenarPorDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorDNIMouseClicked
        modelDuenos.setRowCount(0);
        modelEmpleados.setRowCount(0);
        Collections.sort(listaDuenosOrdenada, new OrdenarDuenoPorDni());
        Collections.sort(listaEmpleadosOrdenada, new OrdenarEmpleadoPorDni());
        Iterator k = listaDuenosOrdenada.listIterator();
        while(k.hasNext()){
            Dueño d = (Dueño) k.next();
            modelDuenos.addRow(new Object []{d.getNombre(),d.getApellido(),d.getDni(),d.getTelefonoMovil(),d.getTelefonoFijo(),d.getFechaDeNacimiento(),d.getPuntaje(),d.getEspeciesCreadas(),d.getEscala()});
        }
        Iterator j = listaEmpleadosOrdenada.listIterator();
        while(j.hasNext()){
            Empleado e = (Empleado) j.next();
            modelEmpleados.addRow(new Object []{e.getNombre(),e.getApellido(),e.getDni(),e.getTelefonoMovil(),e.getTelefonoFijo(),e.getFechaDeNacimiento(),e.getPuntaje(),e.getSueldo(),e.getAntiguedad(),e.getBonoExtra()});
        }
    }//GEN-LAST:event_jRadioButtonOrdenarPorDNIMouseClicked

    private void jRadioButtonOrdenarPorPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOrdenarPorPuntajeActionPerformed

    private void jRadioButtonOrdenarPorPuntajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonOrdenarPorPuntajeMouseClicked
        modelDuenos.setRowCount(0);
        modelEmpleados.setRowCount(0);
        Collections.sort(listaDuenosOrdenada, new OrdenarDuenoPorPuntaje());
        Collections.sort(listaEmpleadosOrdenada, new OrdenarEmpleadoPorPuntaje());
        Iterator k = listaDuenosOrdenada.listIterator();
        while(k.hasNext()){
            Dueño d = (Dueño) k.next();
            modelDuenos.addRow(new Object []{d.getNombre(),d.getApellido(),d.getDni(),d.getTelefonoMovil(),d.getTelefonoFijo(),d.getFechaDeNacimiento(),d.getPuntaje(),d.getEspeciesCreadas(),d.getEscala()});
        }
        Iterator j = listaEmpleadosOrdenada.listIterator();
        while(j.hasNext()){
            Empleado e = (Empleado) j.next();
            modelEmpleados.addRow(new Object []{e.getNombre(),e.getApellido(),e.getDni(),e.getTelefonoMovil(),e.getTelefonoFijo(),e.getFechaDeNacimiento(),e.getPuntaje(),e.getSueldo(),e.getAntiguedad(),e.getBonoExtra()});
        }
    }//GEN-LAST:event_jRadioButtonOrdenarPorPuntajeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null,"Esta seguro que desea evaluar usuarios? Esta accion no se puede deshacer","Atencion",JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            Iterator i = setUsuarios.iterator();
            while(i.hasNext()){
                Usuario u = (Usuario) i.next();
                u.evaluacionDeUsuario();
            }
            JOptionPane.showMessageDialog(null,"La evaluacion de usuarios se realizo correctamente.","Info",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            padre.setVisible(true);
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonOrdenarPorDNI;
    private javax.swing.JRadioButton jRadioButtonOrdenarPorPuntaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDuenos;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
